// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnLdYsrZK-Mmp1Y2sitv5T6Mac6ORgs3Y',
    appId: '1:142667221421:web:6ec81cd09c11fa1c9b3924',
    messagingSenderId: '142667221421',
    projectId: 'uniconn-f0931',
    authDomain: 'uniconn-f0931.firebaseapp.com',
    storageBucket: 'uniconn-f0931.firebasestorage.app',
    measurementId: 'G-86WYFRQXEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAEec0j-GJgtWIKgMQ7ERim9Camab08TE',
    appId: '1:142667221421:android:f4e57e23360bd28a9b3924',
    messagingSenderId: '142667221421',
    projectId: 'uniconn-f0931',
    storageBucket: 'uniconn-f0931.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnLdYsrZK-Mmp1Y2sitv5T6Mac6ORgs3Y',
    appId: '1:142667221421:web:7d75091d4f9aa2869b3924',
    messagingSenderId: '142667221421',
    projectId: 'uniconn-f0931',
    authDomain: 'uniconn-f0931.firebaseapp.com',
    storageBucket: 'uniconn-f0931.firebasestorage.app',
    measurementId: 'G-7ZJ0KH9NL8',
  );
}
